runs:

  using: "composite"

  steps:

  - shell: bash
    if: runner.os == 'Linux'
    run: |
      sudo apt update
      sudo apt install --no-install-recommends ninja-build libopenmpi-dev libjpeg-dev
